package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Admins generated by hbm2java
 */
public class Admins implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Column(name = "AdminId")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int adminId;
    @Column(name = "Email")
    private String email;
    @Column(name = "Passwords")
    private String passwords;
    @Column(name = "Fullname")
    private String fullname;
    @Column(name = "Birthday")
    @Temporal(TemporalType.DATE)
    private Date birthday;
    @Column(name = "IdCard")
    private String idCard;
    @Column(name = "Gender")
    private int gender;
    @Column(name = "AdminAddress")
    private String adminAddress;
    @Column(name = "Phone")
    private String phone;
    @Column(name = "Avatar")
    private String avatar;
    @Column(name = "Status")
    private int status;
    @OneToMany(fetch = FetchType.EAGER)
    private Set catalogses = new HashSet(0);
    @OneToMany(fetch = FetchType.EAGER)
    private Set newses = new HashSet(0);
    @OneToMany(fetch = FetchType.EAGER)
    private Set feedbackses = new HashSet(0);

    public Admins() {
    }

    public Admins(int adminId, String email, String passwords, String fullname, Date birthday, String idCard, String adminAddress, String phone) {
        this.adminId = adminId;
        this.email = email;
        this.passwords = passwords;
        this.fullname = fullname;
        this.birthday = birthday;
        this.idCard = idCard;
        this.adminAddress = adminAddress;
        this.phone = phone;
    }

    public Admins(int adminId, String email, String passwords, String fullname, Date birthday, String idCard, int gender, String adminAddress, String phone, String avatar, int status, Set catalogses, Set newses, Set feedbackses) {
        this.adminId = adminId;
        this.email = email;
        this.passwords = passwords;
        this.fullname = fullname;
        this.birthday = birthday;
        this.idCard = idCard;
        this.gender = gender;
        this.adminAddress = adminAddress;
        this.phone = phone;
        this.avatar = avatar;
        this.status = status;
        this.catalogses = catalogses;
        this.newses = newses;
        this.feedbackses = feedbackses;
    }

    public int getAdminId() {
        return this.adminId;
    }

    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswords() {
        return this.passwords;
    }

    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }

    public String getFullname() {
        return this.fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getIdCard() {
        return this.idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public int getGender() {
        return this.gender;
    }

    public void setGender(int gender) {
        this.gender = gender;
    }

    public String getAdminAddress() {
        return this.adminAddress;
    }

    public void setAdminAddress(String adminAddress) {
        this.adminAddress = adminAddress;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Set getCatalogses() {
        return this.catalogses;
    }

    public void setCatalogses(Set catalogses) {
        this.catalogses = catalogses;
    }

    public Set getNewses() {
        return this.newses;
    }

    public void setNewses(Set newses) {
        this.newses = newses;
    }

    public Set getFeedbackses() {
        return this.feedbackses;
    }

    public void setFeedbackses(Set feedbackses) {
        this.feedbackses = feedbackses;
    }

}
