package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brands generated by hbm2java
 */
@Entity
@Table(name = "Brands")
public class Brands implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "BrandId", insertable = false, updatable = false)
    private int brandId;
    @Column(name = "BrandName")
    private String brandName;
    @Column(name = "BrandPiority")
    private int brandPiority;
    @Column(name = "BrandLogo")
    private String brandLogo;
    @Column(name = "BrandStatus")
    private int brandStatus;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "brandId")
    private Set productses = new HashSet(0);

    public Brands() {
    }

    public Brands(int brandId, String brandName, int brandPiority, String brandLogo, int brandStatus) {
        this.brandId = brandId;
        this.brandName = brandName;
        this.brandPiority = brandPiority;
        this.brandLogo = brandLogo;
        this.brandStatus = brandStatus;
    }

    public Brands(int brandId, String brandName, int brandPiority, String brandLogo, int brandStatus, Set productses) {
        this.brandId = brandId;
        this.brandName = brandName;
        this.brandPiority = brandPiority;
        this.brandLogo = brandLogo;
        this.brandStatus = brandStatus;
        this.productses = productses;
    }

    public int getBrandId() {
        return this.brandId;
    }

    public void setBrandId(int brandId) {
        this.brandId = brandId;
    }

    public String getBrandName() {
        return this.brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    public int getBrandPiority() {
        return this.brandPiority;
    }

    public void setBrandPiority(int brandPiority) {
        this.brandPiority = brandPiority;
    }

    public String getBrandLogo() {
        return this.brandLogo;
    }

    public void setBrandLogo(String brandLogo) {
        this.brandLogo = brandLogo;
    }

    public int getBrandStatus() {
        return this.brandStatus;
    }

    public void setBrandStatus(int brandStatus) {
        this.brandStatus = brandStatus;
    }

    public Set getProductses() {
        return this.productses;
    }

    public void setProductses(Set productses) {
        this.productses = productses;
    }

}
