package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catalogs generated by hbm2java
 */
@Entity
@Table(name = "Catalogs")
public class Catalogs implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Column(name = "CatalogId")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int catalogId;
    @Column(name = "CatalogName")
    private String catalogName;
    @Column(name = "Piority")
    private int piority;
    @Column(name = "ParentId")
    private int parentId;
    @Column(name = "CatalogStatus")
    private int catalogStatus;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "catalogId")
    private Set newses = new HashSet(0);

    public Catalogs() {
    }

    public Catalogs(int catalogId, String catalogName, int piority, int parentId, int catalogStatus) {
        this.catalogId = catalogId;
        this.catalogName = catalogName;
        this.piority = piority;
        this.parentId = parentId;
        this.catalogStatus = catalogStatus;
    }

    public Catalogs(int catalogId, String catalogName, int piority, int parentId, int catalogStatus, Set newses) {
        this.catalogId = catalogId;
        this.catalogName = catalogName;
        this.piority = piority;
        this.parentId = parentId;
        this.catalogStatus = catalogStatus;
        this.newses = newses;
    }

    public int getCatalogId() {
        return this.catalogId;
    }

    public void setCatalogId(int catalogId) {
        this.catalogId = catalogId;
    }

    public String getCatalogName() {
        return this.catalogName;
    }

    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }

    public int getPiority() {
        return this.piority;
    }

    public void setPiority(int piority) {
        this.piority = piority;
    }

    public int getParentId() {
        return this.parentId;
    }

    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    public int getCatalogStatus() {
        return this.catalogStatus;
    }

    public void setCatalogStatus(int catalogStatus) {
        this.catalogStatus = catalogStatus;
    }

    public Set getNewses() {
        return this.newses;
    }

    public void setNewses(Set newses) {
        this.newses = newses;
    }

}
