package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "Categories")
public class Categories implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CategoryId", insertable = false, updatable = false)
    private int categoryId;
    @Column(name = "CategoryName")
    private String categoryName;
    @Column(name = "CategoryPiority")
    private int categoryPiority;
    @Column(name = "ParentId")
    private int parentId;
    @Column(name = "ParentName", nullable = true)
    private String parentName;
    @Column(name = "CategoryStatus")
    private int categoryStatus;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "categoryId")
    private Set productses = new HashSet(0);

    public Categories() {
    }

    public Categories(int categoryId, String categoryName, int categoryPiority, int parentId, String parentName, int categoryStatus) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.categoryPiority = categoryPiority;
        this.parentId = parentId;
        this.parentName = parentName;
        this.categoryStatus = categoryStatus;
    }

    public Categories(int categoryId, String categoryName, int categoryPiority, int parentId, String parentName, int categoryStatus, Set productses) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.categoryPiority = categoryPiority;
        this.parentId = parentId;
        this.parentName = parentName;
        this.categoryStatus = categoryStatus;
        this.productses = productses;
    }

    public int getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public int getCategoryPiority() {
        return this.categoryPiority;
    }

    public void setCategoryPiority(int categoryPiority) {
        this.categoryPiority = categoryPiority;
    }

    public int getParentId() {
        return this.parentId;
    }

    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    public String getParentName() {
        return this.parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    public int getCategoryStatus() {
        return this.categoryStatus;
    }

    public void setCategoryStatus(int categoryStatus) {
        this.categoryStatus = categoryStatus;
    }

    public Set getProductses() {
        return this.productses;
    }

    public void setProductses(Set productses) {
        this.productses = productses;
    }

}
