package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Faqs generated by hbm2java
 */
public class Faqs  implements java.io.Serializable {


     private int faqid;
     private String fastQuestion;
     private String fastAnswer;
     private int faqstatus;

    public Faqs() {
    }

    public Faqs(int faqid, String fastQuestion, String fastAnswer, int faqstatus) {
       this.faqid = faqid;
       this.fastQuestion = fastQuestion;
       this.fastAnswer = fastAnswer;
       this.faqstatus = faqstatus;
    }
   
    public int getFaqid() {
        return this.faqid;
    }
    
    public void setFaqid(int faqid) {
        this.faqid = faqid;
    }
    public String getFastQuestion() {
        return this.fastQuestion;
    }
    
    public void setFastQuestion(String fastQuestion) {
        this.fastQuestion = fastQuestion;
    }
    public String getFastAnswer() {
        return this.fastAnswer;
    }
    
    public void setFastAnswer(String fastAnswer) {
        this.fastAnswer = fastAnswer;
    }
    public int getFaqstatus() {
        return this.faqstatus;
    }
    
    public void setFaqstatus(int faqstatus) {
        this.faqstatus = faqstatus;
    }




}


