package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Feedbacks generated by hbm2java
 */
public class Feedbacks implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Column(name = "FeedbackId")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int feedbackId;
    
    @Column(name = "Admins")
    @ManyToOne(optional = false)
    @JoinColumn(name = "AdminId")
    @Transient
    private Admins admins;
    
    @Column(name = "FeedbackCatalogs")
    @ManyToOne(optional = false)
    @JoinColumn(name = "FeedbackCatalogId")
    @Transient
    private FeedbackCatalogs feedbackCatalogs;
    
    @Column(name = "Fullname")
    private String fullname;
    @Column(name = "Phone")
    private String phone;
    @Column(name = "Email")
    private String email;
    @Column(name = "FeedbackAddress")
    private String feedbackAddress;
    @Column(name = "Content")
    private String content;
    @Column(name = "FeedbacksTime")
    @Temporal(TemporalType.TIMESTAMP)
    private Date feedbacksTime;
    @Column(name = "FeedbackStatus")
    private int feedbackStatus;

    public Feedbacks() {
    }

    public Feedbacks(int feedbackId, FeedbackCatalogs feedbackCatalogs, String content, Date feedbacksTime, int feedbackStatus) {
        this.feedbackId = feedbackId;
        this.feedbackCatalogs = feedbackCatalogs;
        this.content = content;
        this.feedbacksTime = feedbacksTime;
        this.feedbackStatus = feedbackStatus;
    }

    public Feedbacks(int feedbackId, Admins admins, FeedbackCatalogs feedbackCatalogs, String fullname, String phone, String email, String feedbackAddress, String content, Date feedbacksTime, int feedbackStatus) {
        this.feedbackId = feedbackId;
        this.admins = admins;
        this.feedbackCatalogs = feedbackCatalogs;
        this.fullname = fullname;
        this.phone = phone;
        this.email = email;
        this.feedbackAddress = feedbackAddress;
        this.content = content;
        this.feedbacksTime = feedbacksTime;
        this.feedbackStatus = feedbackStatus;
    }

    public int getFeedbackId() {
        return this.feedbackId;
    }

    public void setFeedbackId(int feedbackId) {
        this.feedbackId = feedbackId;
    }

    public Admins getAdmins() {
        return this.admins;
    }

    public void setAdmins(Admins admins) {
        this.admins = admins;
    }

    public FeedbackCatalogs getFeedbackCatalogs() {
        return this.feedbackCatalogs;
    }

    public void setFeedbackCatalogs(FeedbackCatalogs feedbackCatalogs) {
        this.feedbackCatalogs = feedbackCatalogs;
    }

    public String getFullname() {
        return this.fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFeedbackAddress() {
        return this.feedbackAddress;
    }

    public void setFeedbackAddress(String feedbackAddress) {
        this.feedbackAddress = feedbackAddress;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getFeedbacksTime() {
        return this.feedbacksTime;
    }

    public void setFeedbacksTime(Date feedbacksTime) {
        this.feedbacksTime = feedbacksTime;
    }

    public int getFeedbackStatus() {
        return this.feedbackStatus;
    }

    public void setFeedbackStatus(int feedbackStatus) {
        this.feedbackStatus = feedbackStatus;
    }

}
