package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1



/**
 * Icons generated by hbm2java
 */
public class Icons  implements java.io.Serializable {


     private int iconId;
     private String iconImage;
     private int iconStatus;

    public Icons() {
    }

    public Icons(int iconId, String iconImage, int iconStatus) {
       this.iconId = iconId;
       this.iconImage = iconImage;
       this.iconStatus = iconStatus;
    }
   
    public int getIconId() {
        return this.iconId;
    }
    
    public void setIconId(int iconId) {
        this.iconId = iconId;
    }
    public String getIconImage() {
        return this.iconImage;
    }
    
    public void setIconImage(String iconImage) {
        this.iconImage = iconImage;
    }
    public int getIconStatus() {
        return this.iconStatus;
    }
    
    public void setIconStatus(int iconStatus) {
        this.iconStatus = iconStatus;
    }




}


