package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1



/**
 * Logo generated by hbm2java
 */
public class Logo  implements java.io.Serializable {


     private int logoId;
     private String logoImage;
     private int logoStatus;

    public Logo() {
    }

    public Logo(int logoId, String logoImage, int logoStatus) {
       this.logoId = logoId;
       this.logoImage = logoImage;
       this.logoStatus = logoStatus;
    }
   
    public int getLogoId() {
        return this.logoId;
    }
    
    public void setLogoId(int logoId) {
        this.logoId = logoId;
    }
    public String getLogoImage() {
        return this.logoImage;
    }
    
    public void setLogoImage(String logoImage) {
        this.logoImage = logoImage;
    }
    public int getLogoStatus() {
        return this.logoStatus;
    }
    
    public void setLogoStatus(int logoStatus) {
        this.logoStatus = logoStatus;
    }




}


