package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "News")
public class News implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Column(name = "NewsId")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int newsId;
    @Column(name = "Admins")
    @ManyToOne(optional = false)
    @JoinColumn(name = "AdminId")
    @Transient
    private Admins admins;
    @Column(name = "Catalogs")
    @ManyToOne(optional = false)
    @JoinColumn(name = "CatalogId")
    @Transient
    private Catalogs catalogs;
    private String newTitle;
    private String newImage;
    private String newDescription;
    private int countView;
    @Column(name = "CreateDate")
    @Temporal(TemporalType.TIMESTAMP)
    private Date createDate;
    private String newContent;
    private int newStatus;

    public News() {
    }

    public News(int newsId, Admins admins, String newTitle, String newImage, String newDescription, int countView, Date createDate, String newContent, int newStatus) {
        this.newsId = newsId;
        this.admins = admins;
        this.newTitle = newTitle;
        this.newImage = newImage;
        this.newDescription = newDescription;
        this.countView = countView;
        this.createDate = createDate;
        this.newContent = newContent;
        this.newStatus = newStatus;
    }

    public News(int newsId, Admins admins, Catalogs catalogs, String newTitle, String newImage, String newDescription, int countView, Date createDate, String newContent, int newStatus) {
        this.newsId = newsId;
        this.admins = admins;
        this.catalogs = catalogs;
        this.newTitle = newTitle;
        this.newImage = newImage;
        this.newDescription = newDescription;
        this.countView = countView;
        this.createDate = createDate;
        this.newContent = newContent;
        this.newStatus = newStatus;
    }

    public int getNewsId() {
        return this.newsId;
    }

    public void setNewsId(int newsId) {
        this.newsId = newsId;
    }

    public Admins getAdmins() {
        return this.admins;
    }

    public void setAdmins(Admins admins) {
        this.admins = admins;
    }

    public Catalogs getCatalogs() {
        return this.catalogs;
    }

    public void setCatalogs(Catalogs catalogs) {
        this.catalogs = catalogs;
    }

    public String getNewTitle() {
        return this.newTitle;
    }

    public void setNewTitle(String newTitle) {
        this.newTitle = newTitle;
    }

    public String getNewImage() {
        return this.newImage;
    }

    public void setNewImage(String newImage) {
        this.newImage = newImage;
    }

    public String getNewDescription() {
        return this.newDescription;
    }

    public void setNewDescription(String newDescription) {
        this.newDescription = newDescription;
    }

    public int getCountView() {
        return this.countView;
    }

    public void setCountView(int countView) {
        this.countView = countView;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getNewContent() {
        return this.newContent;
    }

    public void setNewContent(String newContent) {
        this.newContent = newContent;
    }

    public int getNewStatus() {
        return this.newStatus;
    }

    public void setNewStatus(int newStatus) {
        this.newStatus = newStatus;
    }

}
