package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "Orders")
public class Orders implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "OrderId")
    private int orderId;

    @Column(name = "Customers")
    @ManyToOne(optional = false)
    @JoinColumn(name = "customerId")
    @Transient
    private Customers customers;

    @Column(name = "FullName")
    private String fullName;
    @Column(name = "Email")
    private String email;
    @Column(name = "Phone")
    private String phone;

    @Column(name = "OrderTotalAmount")
    private double orderTotalAmount;
    @Column(name = "OrderNote")
    private String orderNote;
    @Column(name = "OrderAddress")
    private String orderAddress;
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "CreateDate")
    @Temporal(TemporalType.TIMESTAMP)
    private Date createDate;
   
    @Basic(optional = false)
    @NotNull
    @Column(name = "TimeExpired")
    @Temporal(TemporalType.TIMESTAMP)
    private Date timeExpired;
    
    
    @Column(name = "OrderStatus")
    private int orderStatus;
    
    private Set orderDetailses = new HashSet(0);

    public Orders() {
    }

    public Orders(int orderId, Customers customers, String fullName, String email, String phone, double orderTotalAmount,Date createDate,Date timeExpired, int orderStatus) {
        this.orderId = orderId;
        this.customers = customers;
        this.fullName = fullName;
        this.email = email;
        this.phone = phone;
        this.orderTotalAmount = orderTotalAmount;
        this.createDate = createDate;
        this.timeExpired = timeExpired;
        this.orderStatus = orderStatus;
    }

    public Orders(int orderId, Customers customers, String fullName, String email, String phone, double orderTotalAmount, String orderNote, String orderAddress,Date createDate,Date timeExpired, int orderStatus, Set orderDetailses) {
        this.orderId = orderId;
        this.customers = customers;
        this.fullName = fullName;
        this.email = email;
        this.phone = phone;
        this.orderTotalAmount = orderTotalAmount;
        this.orderNote = orderNote;
        this.orderAddress = orderAddress;
        this.createDate = createDate;
        this.timeExpired = timeExpired;
        this.orderStatus = orderStatus;
        this.orderDetailses = orderDetailses;
    }

    public int getOrderId() {
        return this.orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public Customers getCustomers() {
        return this.customers;
    }

    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public double getOrderTotalAmount() {
        return this.orderTotalAmount;
    }

    public void setOrderTotalAmount(double orderTotalAmount) {
        this.orderTotalAmount = orderTotalAmount;
    }

    public String getOrderNote() {
        return this.orderNote;
    }

    public void setOrderNote(String orderNote) {
        this.orderNote = orderNote;
    }

    public String getOrderAddress() {
        return this.orderAddress;
    }

    public void setOrderAddress(String orderAddress) {
        this.orderAddress = orderAddress;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getTimeExpired() {
        return this.timeExpired;
    }

    public void setTimeExpired(Date timeExpired) {
        this.timeExpired = timeExpired;
    }

    public int getOrderStatus() {
        return this.orderStatus;
    }

    public void setOrderStatus(int orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Set getOrderDetailses() {
        return this.orderDetailses;
    }

    public void setOrderDetailses(Set orderDetailses) {
        this.orderDetailses = orderDetailses;
    }

}
