package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "OrderDetailsId")
    private int orderDetailsId;

    @Column(name = "Orders")
    @ManyToOne(optional = false)
    @JoinColumn(name = "OrderId")
    @Transient
    private Orders orders;

    @Column(name = "Products")
    @ManyToOne(optional = false)
    @JoinColumn(name = "productId")
    @Transient
    private Products products;

    @Column(name = "OrderDetailQuantity")
    private int orderDetailQuantity;
    @Column(name = "OrderDetailPrice")
    private double orderDetailPrice;
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "CreatedDate")
    @Temporal(TemporalType.TIMESTAMP)
    private Date createDate;

    @Column(name = "OrderDetailStatus")
    private int orderDetailStatus;
    
    public OrderDetails() {
    }

    public OrderDetails(int orderDetailsId , Orders orders, Products products, int orderDetailQuantity, double orderDetailPrice,Date createDate, int orderDetailStatus) {
        this.orderDetailsId = orderDetailsId;
        this.orders = orders;
        this.products = products;
        this.orderDetailQuantity = orderDetailQuantity;
        this.orderDetailPrice = orderDetailPrice;
        this.createDate = createDate;
        this.orderDetailStatus = orderDetailStatus;
    }

    public int getOrderDetailsId() {
        return this.orderDetailsId;
    }

    public void setOrderDetailsId(int OrderDetailsId) {
        this.orderDetailsId = OrderDetailsId;
    }

    public Orders getOrders() {
        return this.orders;
    }

    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    public Products getProducts() {
        return this.products;
    }

    public void setProducts(Products products) {
        this.products = products;
    }

    public int getOrderDetailQuantity() {
        return this.orderDetailQuantity;
    }

    public void setOrderDetailQuantity(int orderDetailQuantity) {
        this.orderDetailQuantity = orderDetailQuantity;
    }

    public double getOrderDetailPrice() {
        return this.orderDetailPrice;
    }

    public void setOrderDetailPrice(double orderDetailPrice) {
        this.orderDetailPrice = orderDetailPrice;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public int getOrderDetailStatus() {
        return this.orderDetailStatus;
    }

    public void setOrderDetailStatus(int orderDetailStatus) {
        this.orderDetailStatus = orderDetailStatus;
    }
    

}
