package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

/**
 * ProductComments generated by hbm2java
 */
@Entity
@Table(name = "ProductComments")
public class ProductComments implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ProductCommentId")
    private int productCommentId;
    
    @Column(name = "Customers")
    @ManyToOne(optional = false)
    @JoinColumn(name = "customerId")
    @Transient
    private Customers customers;
    
    @Column(name = "Products")
    @ManyToOne(optional = false)
    @JoinColumn(name = "productId")
    @Transient
    private Products products;
    
    private int commentRate;
    
    private String commentContent;
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "CommentTime")
    @Temporal(TemporalType.TIMESTAMP)
    private Date commentTime;
    private int commentStatus;

    public ProductComments() {
    }

    public ProductComments(int productCommentId, int commentRate, Date commentTime, int commentStatus) {
        this.productCommentId = productCommentId;
        this.commentRate = commentRate;
        this.commentTime = commentTime;
        this.commentStatus = commentStatus;
    }

    public ProductComments(int productCommentId, Customers customers, Products products, int commentRate, String commentContent, Date commentTime, int commentStatus) {
        this.productCommentId = productCommentId;
        this.customers = customers;
        this.products = products;
        this.commentRate = commentRate;
        this.commentContent = commentContent;
        this.commentTime = commentTime;
        this.commentStatus = commentStatus;
    }

    public int getProductCommentId() {
        return this.productCommentId;
    }

    public void setProductCommentId(int productCommentId) {
        this.productCommentId = productCommentId;
    }

    public Customers getCustomers() {
        return this.customers;
    }

    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    public Products getProducts() {
        return this.products;
    }

    public void setProducts(Products products) {
        this.products = products;
    }

    public int getCommentRate() {
        return this.commentRate;
    }

    public void setCommentRate(int commentRate) {
        this.commentRate = commentRate;
    }

    public String getCommentContent() {
        return this.commentContent;
    }

    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }

    public Date getCommentTime() {
        return this.commentTime;
    }

    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    public int getCommentStatus() {
        return this.commentStatus;
    }

    public void setCommentStatus(int commentStatus) {
        this.commentStatus = commentStatus;
    }

}
