package entity;
// Generated Aug 1, 2020 2:29:25 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

/**
 * Wishlists generated by hbm2java
 */
public class Wishlists implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Column(name = "WishlistId")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int wishlistId;
    
    @Column(name = "Customers")
    @ManyToOne(optional = false)
    @JoinColumn(name = "customerId")
    @Transient
    private Customers customers;
    
    @Column(name = "Products")
    @ManyToOne(optional = false)
    @JoinColumn(name = "productId")
    @Transient
    private Products products;
    
    
    private int wishlistStatus;

    public Wishlists() {
    }

    public Wishlists(int wishlistId, Products products, int wishlistStatus) {
        this.wishlistId = wishlistId;
        this.products = products;
        this.wishlistStatus = wishlistStatus;
    }

    public Wishlists(int wishlistId, Customers customers, Products products, int wishlistStatus) {
        this.wishlistId = wishlistId;
        this.customers = customers;
        this.products = products;
        this.wishlistStatus = wishlistStatus;
    }

    public int getWishlistId() {
        return this.wishlistId;
    }

    public void setWishlistId(int wishlistId) {
        this.wishlistId = wishlistId;
    }

    public Customers getCustomers() {
        return this.customers;
    }

    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    public Products getProducts() {
        return this.products;
    }

    public void setProducts(Products products) {
        this.products = products;
    }

    public int getWishlistStatus() {
        return this.wishlistStatus;
    }

    public void setWishlistStatus(int wishlistStatus) {
        this.wishlistStatus = wishlistStatus;
    }

}
